William
devhausleipzig/camp-8-midterm-group-1 pull request #17
Opened 2023-01-09 14:55 UTC by TheDoplarEffect

Working carrousel component with Movie posters.

Link not implemented yet since routing isn't working yet.
However, movie ID is stored and ready to be used.

2023-01-10 08:55 UTC, NoHara42 commented
What issue does this PR relate to?

2023-01-10 11:33 UTC, TheDoplarEffect commented
Sorry, this is something i did last weekend in my free time and basically did both of these issues at once.
The carrousel of Cards and each card

2023-01-11 10:16 UTC, NoHara42 requested changes
See comments, do not commit `package-lock.json` files

2023-01-11 10:18 UTC, NoHara42 requested changes
also the pnpm-lock should not be included

2023-01-11 10:23 UTC, NoHara42 commented on src/components/API.tsx
> +class API {
I would prefer you make a custom hook for this

2023-01-11 10:23 UTC, NoHara42 commented on src/components/API.tsx
> +const APIKey = "5de0d3a9c085fde70b8c91f6f6a927f3";
this api logic should be part of a seperate PR

2023-01-11 10:24 UTC, NoHara42 commented on src/components/InputForm.tsx
> +import axios from "axios";
I'm assuming this is the searchbar, seperate PR

2023-01-11 10:27 UTC, NoHara42 commented
too many files for one PR, please limit each PR's content to the issues that it relates to

2023-01-11 10:41 UTC, NoHara42 commented on src/layouts/index.ts
> +export * from "./RootLayout";
why do you need this

2023-01-11 10:50 UTC, NoHara42 commented on src/components/Movie.tsx
> +import axios from "axios";
which issue does Movie.tsx defer to?

2023-01-11 10:53 UTC, NoHara42 commented on src/main.tsx
> +  {
Shouldn't this have been handled in the routing issue? #15

2023-01-11 10:53 UTC, NoHara42 commented on src/routes/Input.tsx
> +  <InputForm></InputForm>;
This seems redundant

2023-01-11 10:54 UTC, NoHara42 commented on src/routes/Login.tsx
> +      <InputForm></InputForm>
Is this just placeholder content?

2023-01-11 10:56 UTC, NoHara42 commented on src/stories/API.stories.tsx
> +import React from "react";
having a story for something as abstract as an api is a bit odd, let's only make stories for visual elements

2023-01-11 10:57 UTC, NoHara42 requested changes
See comments and please extract changes to separate PRs based on the issue they concern

2023-01-11 20:16 UTC, closed without merging