Genres
devhausleipzig/camp-8-midterm-group-1 pull request #18
Opened 2023-01-10 08:27 UTC by TheDoplarEffect

Cerated an Emoji Component.  Background colour is hardcoded and will need to be refactored once tailwind config is done.
Enums were used

2023-01-10 08:59 UTC, NoHara42 commented
Which Issue does this relate to?

2023-01-10 11:00 UTC, NoHara42 commented
Tailwind setup is on main, please reverse merge

2023-01-10 11:49 UTC, TheDoplarEffect commented
Have merged main on my machine and added tailwind classes to component

2023-01-11 10:59 UTC, NoHara42 commented on src/stories/Emogi.stories.tsx
> +import "../index.css";
you shouldn't need to import this here

2023-01-11 11:00 UTC, NoHara42 requested changes
remove -lock.json files and see small change

2023-01-12 08:38 UTC, closed without merging