Searchbar
devhausleipzig/camp-8-midterm-group-1 pull request #19
Opened 2023-01-10 09:02 UTC by n1lsw

# 8 - I created a searchbar component including a story

2023-01-10 11:15 UTC, NoHara42 commented on src/components/Button.tsx
> +        className="rounded-md h-[48px] w-[335px] bg-[#FFB43A]"
don't overuse tailwind square bracket notation, h-12, and a bg-someCustomColorName should be used here.

w-[335px] is fine if you don't reuse that width

2023-01-10 11:16 UTC, NoHara42 commented on src/components/SearchBar.tsx
> +    // const fromEntries = formData.entries();
don't commit comment blocks

2023-01-10 11:17 UTC, NoHara42 commented on src/components/SearchBar.tsx
> +                className="p-1 focus:outline-none focus:shadow-outline text-[#FFFFFF] opacity-40"
why not use -white instead of -[#FFFFFF]

2023-01-10 11:18 UTC, NoHara42 commented on src/components/SearchBar.tsx
> +              className="py-2 text-sm text-[#FFFFFF] rounded-full bg-[#363740] h-[48px] w-[335px] hover:border-2 hover:border-[#FFFFFF] hover:border-opacity-40 pl-10 focus:outline-none"
same here, think about extracting similar sets of utility classes to custom css classes

2023-01-10 15:06 UTC, n1lsw commented
Please ignore the comment block in the beginning. It is part of the code, but I needed to comment it to have storybook to run

2023-01-11 11:01 UTC, NoHara42 commented on package.json
> +    "serve": "^14.1.2",
why is serve a dependency here

2023-01-11 11:03 UTC, NoHara42 commented on src/components/Movie.tsx
> +import axios from "axios";
should be part of #23, not the searchbar issue PR

2023-01-11 11:04 UTC, NoHara42 commented on src/components/Test.tsx
> +import { API } from "./API";
do not commit test components

2023-01-11 11:07 UTC, NoHara42 requested changes
please address all my comments before sending a PR back to review.
remove -lock.json files and replace .svgs in assets with heroicon in-file imports

2023-01-11 15:07 UTC, n1lsw commented on package.json
> +    "serve": "^14.1.2",
deleted line 26

2023-01-11 15:08 UTC, n1lsw commented on src/components/Movie.tsx
> +import axios from "axios";
removed it

2023-01-11 15:08 UTC, n1lsw commented on src/components/Test.tsx
> +import { API } from "./API";
deleted it

2023-01-12 08:35 UTC, NoHara42 commented on package.json
> +    "react-icons": "^4.7.1",
where is react-icons used?

2023-01-12 08:36 UTC, NoHara42 commented on package.json
> +    "@storybook/react": "7.0.0-beta.19",
not necessary to fix the version number

2023-01-12 08:38 UTC, NoHara42 commented
@n1lsw please see all my comments above and address them individually before sending it back for review

https://github.com/devhausleipzig/camp-8-midterm-group-1/pull/19#pullrequestreview-1243713325

remove all lock files (package-lock.json, pnpm-lock.yaml), and address other comments please

2023-01-12 09:13 UTC, NoHara42 approved these changes
LGTM

2023-01-12 09:13 UTC, merged