Login
devhausleipzig/camp-8-midterm-group-1 pull request #20
Opened 2023-01-10 09:04 UTC by n1lsw

# 5 I created a login component / page with a story.

2023-01-10 11:18 UTC, ReallyBoard123 commented
please pull the updated main , and merge it into your branch to avoid merge conflicts

2023-01-11 11:09 UTC, NoHara42 commented on package.json
> +    "serve": "^14.1.2",
why is serve here

2023-01-11 11:10 UTC, NoHara42 commented on src/components/API.tsx
> +import axios from "axios";
this should be part of a separate PR

2023-01-11 15:04 UTC, n1lsw commented on package.json
> +    "serve": "^14.1.2",
I dont know. I never installed it/touched this files. But I will remove it.

2023-01-11 15:05 UTC, n1lsw commented on src/components/API.tsx
> +import axios from "axios";
Removed it

2023-01-12 08:10 UTC, ReallyBoard123 commented on src/components/Button.tsx
> +        className="rounded-md h-[48px] w-[335px] bg-[#FFB43A]"
try avoiding using these [ ], and find the tailwind classes for these :)

2023-01-12 08:11 UTC, ReallyBoard123 commented on src/layouts/RootLayout.tsx
> +<<<<<<< HEAD
Is this from a merge conflict in your code?

2023-01-12 08:16 UTC, ReallyBoard123 commented on src/components/Input.tsx
> +      className="w-96 h-[667px] bg-dark flex flex-col rounded-md"
please avoid using these absolutes and find the tailwind classes

2023-01-12 08:16 UTC, ReallyBoard123 commented on src/components/Input.tsx
> +              <svg
HeroIcons?

2023-01-12 08:31 UTC, ReallyBoard123 requested changes
So the input component looks great; just a few styling changes need to match the original design,

- [x] the text changes to white when the user will be typing in the form
- [x] the input form needs to be centered


On the other note, I see a few things in the branch that are not part of this issue, but are here to be reviewed?

2023-01-12 11:40 UTC, TheDoplarEffect commented
Also, will look different in Storybook than in Figma file.  Have set width to full so that it addapts to screen size

2023-01-16 08:31 UTC, ReallyBoard123 commented
Who all are working on this? @n1lsw ? or @TheDoplarEffect ?

2023-01-16 08:41 UTC, TheDoplarEffect commented
Nils started the process and I took over the final reviews last week since he was OOO

2023-01-16 09:00 UTC, ReallyBoard123 requested changes
So, this issue looks into creating a login page. This issue has two requirements. 
1. Button Component
2. Input Component

Currently, in this issue I noticed that input component is being used as a substitute for the login page. This issue cannot be completed before the other two issues can be closed. 

I also did not find any branch that tackles the issue for input component.

2023-01-17 13:55 UTC, n1lsw reviewed
I deleted the Button.tsx

2023-01-18 08:10 UTC, ReallyBoard123 requested changes
Previous comments are still not resolved.

2023-01-18 13:32 UTC, ReallyBoard123 approved these changes
@n1lsw 

hey, so the component that you had worked great visually, but had many nested elements. Dan showed me a way to be able to change the props in a way, that could also accept icons as props with pre-configured classNames. I thought that was a very clear solution. So I went around to update the Icon component with all the new codes, resolved the merge conflicts and updated the file. 

I have left a chunk of code in the Login page as comments, try it out and see how the new Input component works. Basically, now you can implement this in any form. Sorry about editing the code.

2023-01-18 13:32 UTC, merged