Regina
devhausleipzig/camp-8-midterm-group-1 pull request #25
Opened 2023-01-10 10:17 UTC by Regi-Rexus

2023-01-10 10:57 UTC, ReallyBoard123 commented on src/components/Button.tsx
> +        data-ripple-light="true"
what is this data-ripple-light?

2023-01-10 11:02 UTC, ReallyBoard123 commented on src/components/Button.tsx
> +        ButtonDisabled
button disabled is with the color yellow-dimmed

[figma](https://www.figma.com/file/TOCJzJFMXE7PL1dQyGWqXZ/camp-8-midterm?node-id=195%3A297&t=mG5belyeS5OPGxSa-4)

2023-01-10 11:04 UTC, ReallyBoard123 commented on src/components/hello.tsx
> +export function Hello() {
Which issue/task is this component referring

2023-01-10 11:15 UTC, ReallyBoard123 requested changes
Try if you can get the button to accept its various states as a prop, and depending upon the prop state (default - primary, secondary, or disabled) - you may use clsx to change styling

2023-01-10 12:36 UTC, Regi-Rexus commented on src/components/hello.tsx
> +export function Hello() {
this was just a test, it can be deleted and I will do it

2023-01-10 12:38 UTC, Regi-Rexus commented on src/components/Button.tsx
> +        data-ripple-light="true"
do you know the feeling, when you just copy+paste things and it works, so you don't look back..? exactly.
(will delete, bc not necessary)

2023-01-12 08:04 UTC, ReallyBoard123 commented on src/components/Button.tsx
> +type ButtonProps = {
Heyy, also add all the original button props to this button which are native to a button, otherwise we will not be able to pass things like onClick to this button

2023-01-12 08:05 UTC, ReallyBoard123 commented on src/main.tsx
> +import { Button } from "./components/Button";
is this an unused import?

2023-01-12 08:06 UTC, ReallyBoard123 requested changes
This is one of the best buttons I have seen!! I am jealous of how neat everything looks :D just a minor things here and there !

2023-01-13 09:48 UTC, Regi-Rexus commented
such kind words! Thanks a lot

2023-01-13 11:35 UTC, ReallyBoard123 commented on src/components/Button.tsx
> +  setFunction: React.Dispatch<React.SetStateAction<string>>;
<img width="683" alt="buttonDestructuring" src="https://user-images.githubusercontent.com/109514645/212311095-e3529b87-42b2-451f-92ee-42b3526c9826.png">
This is what I mean from that the <Button/> with the capital B would not have access to all the native button Props at the top level to destructure.

2023-01-13 11:38 UTC, ReallyBoard123 requested changes
Please try to pass all the button props to the top level

2023-01-16 09:18 UTC, ReallyBoard123 requested changes
@TheDoplarEffect, can you please communicate with the team on the task's status before making a pull request? I do not see any updates in the code. I prefer if the person initially assigned this task makes a pull request themselves or sends some update once they are done with the previous comments.

2023-01-16 13:34 UTC, Regi-Rexus commented
I changed something in Home.tsx because I couldnt remember what I changed last week. changed it back! sorry Chirag!!!

2023-01-16 16:23 UTC, merged