10 create userinfo component thierry
devhausleipzig/camp-8-midterm-group-1 pull request #26
Opened 2023-01-10 12:45 UTC by peelerzin

hey,

Here is the pull request for the issue10. I used tailwind config to design the component and created a story for it. No padding is added or whatever because it will be create with the layer above. 

skrrr :)

2023-01-10 14:06 UTC, ReallyBoard123 commented on src/components/UserInfo.tsx
> +import axios from "axios";
delete unused imports

2023-01-10 14:12 UTC, ReallyBoard123 commented on src/components/UserInfo.tsx
> +      <div className="flex flex-row justify-between w-80">
why do we need this w-80 here?

2023-01-10 14:12 UTC, ReallyBoard123 commented on src/components/UserInfo.tsx
> +            <p>👋</p>
this can just be in the same p tag as above, need not make another p tag

2023-01-10 14:13 UTC, ReallyBoard123 requested changes
the code looks overall great, just clean the file a bit :)

2023-01-10 14:18 UTC, peelerzin commented on src/components/UserInfo.tsx
> +import axios from "axios";
deleted.

2023-01-10 14:45 UTC, peelerzin commented on src/components/UserInfo.tsx
> +      <div className="flex flex-row justify-between w-80">
deleted only justify-between is needed.

2023-01-12 07:48 UTC, ReallyBoard123 commented on src/components/CastCrewButtons.tsx
> +export function CastCrewButtons() {
This is not part of the #10 please remove it from here, or move it to some other branch

2023-01-12 07:49 UTC, ReallyBoard123 requested changes
please do not start other components in the same branch

2023-01-12 08:41 UTC, peelerzin commented on src/components/CastCrewButtons.tsx
> +export function CastCrewButtons() {
Ok I removed the component and story  CastCrewButtons.

2023-01-12 09:27 UTC, ReallyBoard123 approved these changes

2023-01-12 09:36 UTC, merged