12 nav bar component
devhausleipzig/camp-8-midterm-group-1 pull request #27
Opened 2023-01-10 14:06 UTC by ArthiRagothaman

Updated the NavBar component with icons, styles.
Included the hero-icons and added usestate hooks.

2023-01-10 14:18 UTC, ReallyBoard123 commented on src/layouts/NavigationsBar.tsx
> +        {/* <NavLink
kindly delete all the commented block and chunks of code from the file

2023-01-10 14:23 UTC, ReallyBoard123 commented on src/components/NavigationBar.tsx
>  export function NavigationBar() {
where will this be used in the app?

2023-01-10 14:24 UTC, ReallyBoard123 commented on src/layouts/NavigationsBar.tsx
> +  return (
please see if hardcoding w and h can be avoided! please use pre-set tailwind config for these. 

or use w/h using tailwind parameters

2023-01-10 14:24 UTC, ReallyBoard123 commented on src/layouts/NavigationsBar.tsx
> +      <nav className="flex items-center justify-center mt-5 mx-3 ">
Is this possible to map over a set of icons and write the clsx tailwind classes once?

2023-01-10 14:44 UTC, ReallyBoard123 commented on src/layouts/NavigationsBar.tsx
> +export default function Navigationsbar() {
please name the functions using the conventions

2023-01-10 14:45 UTC, ReallyBoard123 requested changes
please resolve the comments :) You are almost there!!

2023-01-10 16:00 UTC, ReallyBoard123 requested changes
- all the previous comments have not been resolved/addressed
- please also link the issue that this pull request is addressing
- please go through the issue that it references, and checkbox the tasks that have been completed in these files

2023-01-10 17:48 UTC, ArthiRagothaman commented
In response to ur comments:
Deleted the commented lines and updated the naming conventions.
Attached the branch name in development section.
All changes done.

2023-01-12 07:23 UTC, ReallyBoard123 commented on src/components/NavigationBar.tsx
>  export function NavigationBar() {
Has this been resolved? This seems to be unaddressed. Where is this going to be used?

2023-01-12 07:33 UTC, ReallyBoard123 commented on src/layouts/Navigationsicons.tsx
> +export default function Navigationsicons() {
please follow the correct naming conventions for functions

2023-01-12 07:43 UTC, ReallyBoard123 commented on src/layouts/Navigationsicons.tsx
> +  const [selected, setSelected] = useState(0);
there shouldn't be any need for a useState here, since you can use className={({ isActive }) in Navlink. On further examination, a duplicate of the file actually exists in the folder structure by the name RootLayout, which already has a solution commented out in it. Please see if you can use that file, rename it properly and make the icons work. The icons are not supposed to just change the styling when clicked, but supposed to "navigate" from page A to page B. and when the navigation happens, styling changes

2023-01-12 07:45 UTC, ReallyBoard123 requested changes
Please try to look into how the navigation layout will function. It might be easier to understand the coding part when you can visualize its function or usage. There are some empty files in the branch; if they are empty and have no purpose for a future usage, please delete them.

2023-01-12 13:56 UTC, ArthiRagothaman commented
Task#2 
Required to create separate NavigationBar component. I found it was easier to have directly write the code in NavigationLayout itself.

2023-01-12 13:59 UTC, ReallyBoard123 approved these changes
Hey Arthi!! Job well done!! I am so happy to see that you got through all the tasks, and made great progress in such little time. I look forward to seeing such complete pull requests in future as well!

2023-01-12 13:59 UTC, merged