Simple Emogi Component
devhausleipzig/camp-8-midterm-group-1 pull request #35
Opened 2023-01-12 08:42 UTC by TheDoplarEffect

Component takes a string as a prop (One of the possible Genres) and displays an Emogi in square

2023-01-13 09:10 UTC, ReallyBoard123 commented on src/components/Emogi.tsx
> +      <p className="text-3xl flex justify-center items-center w-14 h-14 bg-dark-light rounded-xl">
text-3xl can actually be predefined in the tailwind config itself.I see that the typography is part of design system. Please update the tailwind config too, and use the appropriate classes from here: https://www.figma.com/file/TOCJzJFMXE7PL1dQyGWqXZ/camp-8-midterm?node-id=193%3A26&t=jUUOOxf7k14aMcI3-1

2023-01-13 09:12 UTC, ReallyBoard123 requested changes
The component looks very good overall. I would also like to see how the component looks like, when you render 4 of them. Is that possible to implement the same in the stories?

2023-01-13 09:54 UTC, TheDoplarEffect commented
On the Home page we will map over the different Emogis we want to show using these components

2023-01-13 13:16 UTC, ReallyBoard123 commented
The other comments are still unresolved?

2023-01-16 09:56 UTC, ReallyBoard123 approved these changes
looks great!

2023-01-16 09:57 UTC, merged