Cast and Crew Buttons
devhausleipzig/camp-8-midterm-group-1 pull request #39
Opened 2023-01-13 11:17 UTC by TheDoplarEffect

Cast and Crew in the Cast.tsx routes folder.

File uses two sub components, the cast and Crew Buttons and the Movies Action Button which is just them with a square.

When running on vite server works (http://127.0.0.1:5174/movie/500/castcrew)

Also added some animations from switching between pages.

On figma file the scrollable list didn't reach to the end of the page so whole component had to be wrapped in a div with a bottom padding.  However, using the measurements from the figma file it doesn't look anywhere close.  Used pb-12 instead since it looked the closest to original design.

2023-01-13 11:22 UTC, TheDoplarEffect commented
Things I forgot to mention:

- Added custom classes to css to remove scrollbar
- added placeholder image incase profile picture can't be loaded (common with smaller movies or crew members)
- Added a new function to the API

2023-01-13 13:39 UTC, dnmct requested changes

2023-01-13 13:39 UTC, dnmct commented on src/components/CastCrew.tsx
> +type input = {
Pls titlecase Types
Convention: Append Props to the typename to make it clear

2023-01-13 13:39 UTC, dnmct commented on src/components/CastCrew.tsx
> +      <p
Make that a button if it's intended to be clickable

2023-01-13 13:39 UTC, dnmct commented on src/components/MoviesActionButton.tsx
> +type Input = {
the name MoviesActionButton is a bit misleading since this component is not interactive

2023-01-17 11:00 UTC, ReallyBoard123 commented on src/components/CreditsProfile.tsx
> +    <div className="flex items-center gap-[1.25rem]">
Isn`t there a tailwind class here that can be used? or was it in order to keep it consistent to the figma design?

2023-01-17 11:04 UTC, ReallyBoard123 requested changes
Everything looks great! It works as intended. I love the creative touch of the animation. There is a slight inconsistency when one switches from Cast to Crew and back to Cast; the animation ends abruptly or relatively quickly.

Just see if there is an alternative to the tailwind class for the [1.25 rem] you used there. Otherwise, all good.

2023-01-17 12:18 UTC, TheDoplarEffect commented
Changed the custom file.
The jittering in the animation is caused when someone clicks on the enxt button before the animation has finished.

2023-01-18 09:44 UTC, ReallyBoard123 approved these changes

2023-01-18 09:47 UTC, dnmct approved these changes

2023-01-18 09:47 UTC, merged