2by2 images
devhausleipzig/camp-8-midterm-group-1 pull request #41
Opened 2023-01-13 18:28 UTC by TheDoplarEffect

Our component with 4 images per page and five buttons underneath.
Added pazaaz with a animation changing between pages (getting this to work was 90% of time spent).
Each Image is a Link to the relavant location (not yet part of Main)

2023-01-13 18:32 UTC, TheDoplarEffect commented
I've left the Storybook component used to design the item, however, now that we have the LoaderFucntion it no longer works.  File can be deleted if needs be

2023-01-13 18:35 UTC, TheDoplarEffect commented
The final project already works on vite server.  under /movies

2023-01-16 10:03 UTC, ReallyBoard123 commented on src/routes/Movies.tsx
> +  const [previousvalue, setpreviousvalue] = useState(0);
naming convention

2023-01-16 10:04 UTC, ReallyBoard123 commented on src/components/MoviesPageButton.tsx
> +  number: number;
please use a different binding name

2023-01-16 10:07 UTC, ReallyBoard123 commented on src/components/MoviesPageButton.tsx
> +export default function Moviespagebutton({ number, setNumber }: Input) {
use PascalCase

2023-01-16 10:08 UTC, ReallyBoard123 requested changes
this is one of the best looking components in the project so far! and well done with the extra effort on the animation. Could you please go through all the files and use the proper naming conventions?

2023-01-18 10:04 UTC, ReallyBoard123 requested changes
previous comments still not resolved

2023-01-18 10:16 UTC, peelerzin commented on src/components/MoviesPageButton.tsx
> +export default function Moviespagebutton({ number, setNumber }: Input) {
This one is now changed using PascalCase.  MoviesPageButton.

2023-01-18 10:31 UTC, peelerzin commented on src/routes/Movies.tsx
> +  const [previousvalue, setpreviousvalue] = useState(0);
solved.

2023-01-18 10:31 UTC, peelerzin commented on src/components/MoviesPageButton.tsx
> +  number: number;
solved with other binding name

2023-01-18 13:39 UTC, ReallyBoard123 commented on src/components/MoviesPageButton.tsx
> +  setNumber: React.Dispatch<React.SetStateAction<number>>;
would it not be setInputNumber?

2023-01-18 13:43 UTC, ReallyBoard123 commented on src/routes/Movies.tsx
> +  const [previousvalue, setpreviousvalue] = useState(0);
was it resolved?
if it was... why do we still have this in lowercase here:
const [previousvalue, setpreviousvalue]

2023-01-18 13:45 UTC, TheDoplarEffect commented
Corrected typing...

2023-01-18 13:47 UTC, ReallyBoard123 requested changes
... @peelerzin, that was confusing to go through the file and then read a comment from you saying that something has been resolved when it was not. 

Your component looks well done! I am waiting forward to merging it! But please, please go through all the files and change the names according to the conventions. It is very frustrating to go through each line of code every single time of this pull request and point at the same thing again and again

2023-01-18 13:58 UTC, peelerzin commented
We tried with William to fix it this morning, now we going to respect all the conventions by checking all the pages. :)

2023-01-19 10:12 UTC, ReallyBoard123 approved these changes
you did it!

2023-01-19 10:15 UTC, merged