31 create movie detail page
devhausleipzig/camp-8-midterm-group-1 pull request #45
Opened 2023-01-17 20:22 UTC by TheDoplarEffect

Movie detail page, 

details on the movie were added with normal API request of Type MovieDetail.  Since we also needed the writer and director a seperate request was made, these values spread onto the first API request and the type Movie detail modified to reflect that.

Cast and crew button will take them to the relevant page once it is merged.

Custom CSS class was needed to get the poster image to fit in a nice way.

2023-01-18 14:38 UTC, ReallyBoard123 requested changes
- [x] spacing between the movie description text
- [x] spacing between castCrewButton and director text
- [x] movie image is being cutoff, check object fit
- [ ] get reservation button not working

2023-01-18 19:51 UTC, peelerzin commented
Space between movie description and between castcrew buttons and text applied. Image changed to object-fit. Reservation button redirect to Select Time and Date page.

2023-01-19 11:10 UTC, ReallyBoard123 commented on src/routes/Movie.tsx
> +          <p className=" leading-6 text-body text-white-dimmed pt-3">
you will notice a package called line clamp that has been preinstalled in your project. Please use that to limit the lines to 3

line-clamp-3

2023-01-19 11:11 UTC, ReallyBoard123 requested changes
almost there!! This looks great :)

2023-01-19 11:51 UTC, peelerzin commented on src/routes/Movie.tsx
> +          <p className=" leading-6 text-body text-white-dimmed pt-3">
line-clamp-3 added

2023-01-19 13:36 UTC, merged