SeatSquares
devhausleipzig/camp-8-midterm-group-1 pull request #60
Opened 2023-01-18 12:30 UTC by Khorshid23

Basic SeatSqures

2023-01-19 12:57 UTC, ReallyBoard123 requested changes
So, semantically - the best would be to use a checkbox and use the styling aspect on that. Tailwind allows you to have a disabled property on it, and it also accepts a prop called disabled. The other idea would be to make it a button, perhaps easier to style it - and also takes a prop for disabled (reserved)

2023-01-20 08:50 UTC, Khorshid23 commented
we have converted to a button and we removed the state function since it would be done in the upper layer.

2023-01-20 08:53 UTC, ReallyBoard123 commented
@TheDoplarEffect why are you making commits on an issue that you are not assigned to?

2023-01-20 09:03 UTC, TheDoplarEffect commented
There was a bug on her computer and I was helping her out with the Button typeScript names.
I have assigned myself now as well

2023-01-20 09:59 UTC, ReallyBoard123 commented on src/components/SeatSquares.tsx
> +export function SeatSquares({ square, ...props }: ButtonProps) {
This is a single seat, so ideally the naming convention would follow that. SeatSquare or just call it Seat. Squares makes it confusing

2023-01-20 10:00 UTC, ReallyBoard123 commented on src/components/SeatSquares.tsx
> +  square: Options;
what are these Options?

2023-01-20 10:17 UTC, ReallyBoard123 commented
@Khorshid23 @TheDoplarEffect, I updated the seat component. Please try it once to see if this is working. Ideally, see if it is taking onClick handler to change the status. I added id props because it might be easier to track which seat to select. Mapping also gets more manageable. Also when adding ...props, make sure to also give it to the component below

2023-01-20 11:14 UTC, Khorshid23 commented
we changed one of the props from available to reserved and we tested the buttons .I 

https://user-images.githubusercontent.com/116277591/213682339-a12b7fc1-5329-4ec0-91c8-c4cddd7ad40b.mov

would attach the file

2023-01-20 13:11 UTC, ReallyBoard123 approved these changes

2023-01-20 13:12 UTC, merged